[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
space_castle = "9M2kfet4NAaJyz7Uavx4GAjUexqZrZ6ozoA3QGbkRZHK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mico/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
