name: Run tests
run-name: ${{ gitea.actor }} is testing out 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ./start_local_validator
      - run: cargo test
